using Microsoft.EntityFrameworkCore;
using Server.Data;
using Server.Models;
using Server.Tests.Helpers;
using TaskStatus = Server.Models.TaskStatus;

namespace Server.Tests.Data;

/// <summary>
/// Unit tests for the AppDbContext class.
/// These tests verify the database context configuration and entity relationships.
/// </summary>
public class AppDbContextTests : IDisposable
{
    private readonly AppDbContext _context;

    public AppDbContextTests()
    {
        _context = TestDbContextFactory.CreateInMemoryContext();
    }

    public void Dispose()
    {
        _context.Database.EnsureDeleted();
        _context.Dispose();
    }

    #region DbSet Tests

    [Fact]
    public void DbContext_HasUsersDbSet()
    {
        // Assert
        Assert.NotNull(_context.Users);
    }

    [Fact]
    public void DbContext_HasTasksDbSet()
    {
        // Assert
        Assert.NotNull(_context.Tasks);
    }

    #endregion

    #region User Entity Tests

    [Fact]
    public async Task User_CanBeCreated()
    {
        // Arrange
        var user = new User
        {
            Name = "Test User",
            Email = "test@example.com",
            Password = "hashedpassword",
            Role = "User",
            IsEmailVerified = false,
            CreatedAt = DateTime.UtcNow
        };

        // Act
        _context.Users.Add(user);
        await _context.SaveChangesAsync();

        // Assert
        var savedUser = await _context.Users.FindAsync(user.Id);
        Assert.NotNull(savedUser);
        Assert.Equal("Test User", savedUser.Name);
    }

    [Fact]
    public async Task User_IdIsAutoGenerated()
    {
        // Arrange
        var user = new User
        {
            Name = "Test",
            Email = "test@example.com",
            Password = "hash",
            Role = "User",
            CreatedAt = DateTime.UtcNow
        };

        // Act
        _context.Users.Add(user);
        await _context.SaveChangesAsync();

        // Assert
        Assert.True(user.Id > 0);
    }

    [Fact]
    public async Task User_EmailIndexIsConfigured()
    {
        // Arrange & Act - Verify the email index is configured in model
        // Note: In-memory database doesn't enforce unique constraints,
        // but we can verify the model configuration exists
        var entityType = _context.Model.FindEntityType(typeof(User));
        var emailIndex = entityType?.GetIndexes()
            .FirstOrDefault(i => i.Properties.Any(p => p.Name == "Email"));

        // Assert
        Assert.NotNull(emailIndex);
        Assert.True(emailIndex.IsUnique);
    }

    [Fact]
    public async Task User_CanBeUpdated()
    {
        // Arrange
        var user = new User
        {
            Name = "Original Name",
            Email = "test@example.com",
            Password = "hash",
            Role = "User",
            CreatedAt = DateTime.UtcNow
        };
        _context.Users.Add(user);
        await _context.SaveChangesAsync();

        // Act
        user.Name = "Updated Name";
        user.UpdatedAt = DateTime.UtcNow;
        await _context.SaveChangesAsync();

        // Assert
        var updatedUser = await _context.Users.FindAsync(user.Id);
        Assert.Equal("Updated Name", updatedUser!.Name);
        Assert.NotNull(updatedUser.UpdatedAt);
    }

    [Fact]
    public async Task User_CanBeDeleted()
    {
        // Arrange
        var user = new User
        {
            Name = "To Delete",
            Email = "delete@example.com",
            Password = "hash",
            Role = "User",
            CreatedAt = DateTime.UtcNow
        };
        _context.Users.Add(user);
        await _context.SaveChangesAsync();
        var userId = user.Id;

        // Act
        _context.Users.Remove(user);
        await _context.SaveChangesAsync();

        // Assert
        var deletedUser = await _context.Users.FindAsync(userId);
        Assert.Null(deletedUser);
    }

    #endregion

    #region TaskItem Entity Tests

    [Fact]
    public async Task TaskItem_CanBeCreated()
    {
        // Arrange
        TestDbContextFactory.SeedUsers(_context);

        var task = new TaskItem
        {
            Title = "Test Task",
            Description = "Description",
            Status = TaskStatus.Pending,
            Priority = TaskPriority.Medium,
            Category = "Development",
            CreatedByUserId = 1,
            CreatedAt = DateTime.UtcNow
        };

        // Act
        _context.Tasks.Add(task);
        await _context.SaveChangesAsync();

        // Assert
        var savedTask = await _context.Tasks.FindAsync(task.Id);
        Assert.NotNull(savedTask);
        Assert.Equal("Test Task", savedTask.Title);
    }

    [Fact]
    public async Task TaskItem_IdIsAutoGenerated()
    {
        // Arrange
        TestDbContextFactory.SeedUsers(_context);

        var task = new TaskItem
        {
            Title = "Task",
            Description = "Description",
            Status = TaskStatus.Pending,
            Priority = TaskPriority.Low,
            Category = "Test",
            CreatedByUserId = 1,
            CreatedAt = DateTime.UtcNow
        };

        // Act
        _context.Tasks.Add(task);
        await _context.SaveChangesAsync();

        // Assert
        Assert.True(task.Id > 0);
    }

    [Fact]
    public async Task TaskItem_StatusDefaultsToInt()
    {
        // Arrange
        TestDbContextFactory.SeedUsers(_context);

        var task = new TaskItem
        {
            Title = "Task",
            Description = "Description",
            Status = TaskStatus.InProgress,
            Priority = TaskPriority.High,
            Category = "Test",
            CreatedByUserId = 1,
            CreatedAt = DateTime.UtcNow
        };

        // Act
        _context.Tasks.Add(task);
        await _context.SaveChangesAsync();

        // Assert - Reload to check stored value
        var savedTask = await _context.Tasks.FindAsync(task.Id);
        Assert.Equal(TaskStatus.InProgress, savedTask!.Status);
    }

    #endregion

    #region Relationship Tests

    [Fact]
    public async Task TaskItem_HasCreatedByUser_Navigation()
    {
        // Arrange
        TestDbContextFactory.SeedUsers(_context);

        var task = new TaskItem
        {
            Title = "Task with Creator",
            Description = "Description",
            Status = TaskStatus.Pending,
            Priority = TaskPriority.Low,
            Category = "Test",
            CreatedByUserId = 1,
            CreatedAt = DateTime.UtcNow
        };
        _context.Tasks.Add(task);
        await _context.SaveChangesAsync();

        // Act
        var loadedTask = await _context.Tasks
            .Include(t => t.CreatedByUser)
            .FirstOrDefaultAsync(t => t.Id == task.Id);

        // Assert
        Assert.NotNull(loadedTask!.CreatedByUser);
        Assert.Equal("Test User", loadedTask.CreatedByUser.Name);
    }

    [Fact]
    public async Task TaskItem_HasAssignedToUser_Navigation()
    {
        // Arrange
        TestDbContextFactory.SeedUsers(_context);

        var task = new TaskItem
        {
            Title = "Assigned Task",
            Description = "Description",
            Status = TaskStatus.Pending,
            Priority = TaskPriority.Medium,
            Category = "Test",
            CreatedByUserId = 1,
            AssignedToUserId = 2,
            CreatedAt = DateTime.UtcNow
        };
        _context.Tasks.Add(task);
        await _context.SaveChangesAsync();

        // Act
        var loadedTask = await _context.Tasks
            .Include(t => t.AssignedToUser)
            .FirstOrDefaultAsync(t => t.Id == task.Id);

        // Assert
        Assert.NotNull(loadedTask!.AssignedToUser);
        Assert.Equal("Test Admin", loadedTask.AssignedToUser.Name);
    }

    [Fact]
    public async Task TaskItem_AssignedToUser_CanBeNull()
    {
        // Arrange
        TestDbContextFactory.SeedUsers(_context);

        var task = new TaskItem
        {
            Title = "Unassigned Task",
            Description = "Description",
            Status = TaskStatus.Pending,
            Priority = TaskPriority.Low,
            Category = "Test",
            CreatedByUserId = 1,
            AssignedToUserId = null, // Not assigned
            CreatedAt = DateTime.UtcNow
        };

        // Act
        _context.Tasks.Add(task);
        await _context.SaveChangesAsync();

        // Assert
        var loadedTask = await _context.Tasks.FindAsync(task.Id);
        Assert.Null(loadedTask!.AssignedToUserId);
    }

    #endregion

    #region Enum Storage Tests

    [Theory]
    [InlineData(TaskStatus.Pending)]
    [InlineData(TaskStatus.InProgress)]
    [InlineData(TaskStatus.Completed)]
    [InlineData(TaskStatus.Cancelled)]
    public async Task TaskItem_AllStatusValues_StoredCorrectly(TaskStatus status)
    {
        // Arrange
        TestDbContextFactory.SeedUsers(_context);

        var task = new TaskItem
        {
            Title = $"Task with {status}",
            Description = "Description",
            Status = status,
            Priority = TaskPriority.Medium,
            Category = "Test",
            CreatedByUserId = 1,
            CreatedAt = DateTime.UtcNow
        };

        // Act
        _context.Tasks.Add(task);
        await _context.SaveChangesAsync();

        var loadedTask = await _context.Tasks.FindAsync(task.Id);

        // Assert
        Assert.Equal(status, loadedTask!.Status);
    }

    [Theory]
    [InlineData(TaskPriority.Low)]
    [InlineData(TaskPriority.Medium)]
    [InlineData(TaskPriority.High)]
    [InlineData(TaskPriority.Critical)]
    public async Task TaskItem_AllPriorityValues_StoredCorrectly(TaskPriority priority)
    {
        // Arrange
        TestDbContextFactory.SeedUsers(_context);

        var task = new TaskItem
        {
            Title = $"Task with {priority} priority",
            Description = "Description",
            Status = TaskStatus.Pending,
            Priority = priority,
            Category = "Test",
            CreatedByUserId = 1,
            CreatedAt = DateTime.UtcNow
        };

        // Act
        _context.Tasks.Add(task);
        await _context.SaveChangesAsync();

        var loadedTask = await _context.Tasks.FindAsync(task.Id);

        // Assert
        Assert.Equal(priority, loadedTask!.Priority);
    }

    #endregion

    #region Query Tests

    [Fact]
    public async Task Users_CanBeQueriedWithLinq()
    {
        // Arrange
        TestDbContextFactory.SeedUsers(_context);

        // Act
        var admins = await _context.Users
            .Where(u => u.Role == "Admin")
            .ToListAsync();

        // Assert
        Assert.Single(admins);
        Assert.Equal("Test Admin", admins[0].Name);
    }

    [Fact]
    public async Task Tasks_CanBeQueriedWithFilters()
    {
        // Arrange
        TestDbContextFactory.SeedTasks(_context);

        // Act
        var pendingTasks = await _context.Tasks
            .Where(t => t.Status == TaskStatus.Pending)
            .ToListAsync();

        // Assert
        Assert.True(pendingTasks.Count >= 1);
    }

    #endregion
}
